id: A3516A1E7
title: 'The Condensed Essence: A Daily Practice of the Wrathful Guru Takhyung Barwa'
type: translation
pechas:
- I7F826AFE
- IC778E6B7
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:31:09.284171
  last_modified_at: 2023-01-04 11:31:09.284180
  collections:
  - Chatral Rinpoche
  - Works of Tibetan Masters
alignment_to_base:
  I7F826AFE/ED87: A5DF
  IC778E6B7/4444: A5DF
